### ISSUE TITLE
提交新的

### ISSUE THREAD

**Issue by maincooss** [ihmily/ip-info-api#4]
查询本机外网IPv4地址

#curl 4.ipw.cn

#查询本机外网IPv6地址
curl 6.ipw.cn

#测试网络是IPv4还是IPv6访问优先(访问IPv4/IPv6双栈站点，如果返回IPv6地址，则IPv6访问优先)
curl test.ipw.cn

#返回IP 
curl ip.sb 
curl ip.gs
curl ipip.ooo
curl ifconfig.me 
curl ifconfig.io 
curl ifconfig.co 
curl ifconfig.es
curl ifconfig.pro
curl icanhazip.com 
curl ipinfo.io/ip 
curl ipecho.net/ip 
curl ident.me 
curl inet-ip.info
curl eth0.me
curl ipaddr.site
curl ipaddress.sh
curl l2.io/ip
curl tnx.nl/ip
curl wgetip.com
curl 2ip.ru
curl ip.tyk.nu
curl curlmyip.net
curl api.ipify.org
curl ipcalf.com
curl curlmyip.net
curl icanhazip.com
curl checkip.amazonaws.com

curl whatismyip.akamai.com

curl ip-api.com/line?fields=query

#返回IP和地区 
curl cip.cc 
curl ipinfo.io

#利用DNS
dig @ns1.google.com TXT o-o.myaddr.l.google.com +short
nslookup -type=TXT o-o.myaddr.l.google.com ns1.google.com

dig myip.opendns.com @resolver1.opendns.com +short
nslookup myip.opendns.com resolver1.opendns.com

dig whoami.akamai.net. @ns1-1.akamaitech.net +short
nslookup whoami.akamai.net. ns1-1.akamaitech.net

dig @1.1.1.1 whoami.cloudflare ch txt +short

**Comment by NikolaiT** [comment]
curl https://api.ipapi.is

**Comment by ihmily** [comment]
Thanks ！ @maincooss  @NikolaiT
